---

#
# Bootstrap system
#
- hosts: all
  roles:
    - apt-repo-meta
  tags: bootstrap

- hosts: all
  vars:
    apt_meta_packages:
      - apt-utils
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
  roles:
    - apt-meta
  tags: bootstrap

- hosts: all
  roles:
    - locales
  tags: bootstrap

#
# Install roles
#
- hosts: all
  roles: [ cheat.sh ]
  tags: cheat.sh

- hosts: all
  roles: [ cli-utilities ]
  tags: cli-utilities

- hosts: all
  roles: [ docker ]
  tags: docker

- hosts: all
  roles: [ fzf ]
  tags: fzf

- hosts: all
  roles: [ terraform ]
  tags: terraform

- hosts: all
  roles: [ vagrant ]
  tags: vagrant
