---

- name: ensure requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_meta_packages: "{{ vagrant_packages }}"

- name: fetch vagrant info
  uri:
    follow_redirects: "yes"
    method: GET
    return_content: yes
    url: https://www.vagrantup.com/downloads.html
  check_mode: no
  delay: 10
  register: vagrant_info_raw
  retries: 30
  until: vagrant_info_raw is succeeded

- name: set vagrant download url
  check_mode: no
  set_fact:
    vagrant_zip: "{{ vagrant_info_raw.content | regex_search(package_regex) }}"
  vars:
    package_regex: 'https://releases.*linux_amd64\.zip'

- name: ensure vagrant is downloaded
  become: yes
  unarchive:
    dest: "{{ vagrant_path }}"
    mode: 0755
    remote_src: yes
    src: "{{ vagrant_zip }}"
