---

- name: ensure spotify is removed
  include_role:
    name: apt-meta
  vars:
    apt_meta_packages: "{{ [spotify_package_name] }}"
    apt_meta_state: absent

- name: ensure spotify repo is removed
  include_role:
    name: apt-repo-meta
  vars:
    apt_repo_meta_keys:
      - "{{ spotify_apt_key }}"
    apt_repo_meta_repositories:
      - "{{ spotify_apt_repo }}"
    apt_repo_meta_state: absent
