---

- name: ensure requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_meta_packages: "{{ cheat_sh_packages }}"

- name: Download cht.sh
  become: yes
  get_url:
    dest: /usr/local/bin/cht.sh
    mode: '0755'
    url: https://cht.sh/:cht.sh
