---

- name: ensure requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_meta_packages: "{{ fzf_packages }}"

- name: ensure ./local/share directory exists
  file:
    mode: 0755
    path: "{{ fzf_path }}"
    state: directory
  check_mode: no

- name: ensure fzf is cloned
  git:
    clone: yes
    depth: 1
    dest: "{{ fzf_path }}"
    force: yes
    repo: https://github.com/junegunn/fzf
    update: yes

- name: set fzf install command generate rc
  check_mode: no
  set_fact:
    fzf_cmd_rc: "{% if fzf_update_rc %}--update-rc{% else %}--no-update-rc{% endif %}"

- name: set fzf install command shell completion
  check_mode: no
  set_fact:
    fzf_cmd_comp: "{% if fzf_completion %}--completion{% else %}--no-completion{% endif %}"

- name: set fzf install command key bindings
  check_mode: no
  set_fact:
    fzf_cmd_key: "{% if fzf_key_bindings %}--key-bindings{% else %}--no-key-bindings{% endif %}"

- name: ensure fzf install script is run
  changed_when: False
  command: "{{ fzf_path }}/install --bin --64"

- name: ensure fzf configure script is run
  changed_when: False
  command: "{{ fzf_path }}/install {{ fzf_cmd_rc }} {{ fzf_cmd_comp }} {{ fzf_cmd_key }}"
