---

- name: check if fzf uninstall script exists
  stat:
    path: "{{ fzf_path }}/uninstall"
  register: fzf_uninstall_path

- name: ensure fzf configuration is removed
  changed_when: False
  command: "{{ fzf_path }}/uninstall"
  when: fzf_uninstall_path.stat.exists

- name: ensure fzf is removed
  file:
    path: "{{ fzf_path }}"
    state: absent
