---

- name: ensure apt packages are managed
  apt:
    autoclean: yes
    autoremove: yes
    cache_valid_time: 3600
    force_apt_get: yes
    install_recommends: yes
    name: "{{ packages }}"
    state: "{{ apt_meta_state }}"
    update_cache: yes
  become: yes
  vars:
    packages: "{{ apt_meta_packages }}"
