---

- name: ensure requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_meta_packages: "{{ terraform_packages }}"

- name: fetch terraform info
  uri:
    follow_redirects: "yes"
    method: GET
    return_content: yes
    url: https://www.terraform.io/downloads.html
  check_mode: no
  delay: 10
  register: terraform_info_raw
  retries: 30
  until: terraform_info_raw is succeeded

- name: set terraform download url
  check_mode: no
  set_fact:
    terraform_zip: "{{ terraform_info_raw.content | regex_search(package_regex) }}"
  vars:
    package_regex: 'https://releases.*linux_amd64\.zip'

- name: ensure terraform is downloaded
  become: yes
  unarchive:
    dest: "{{ terraform_path }}"
    mode: 0755
    remote_src: yes
    src: "{{ terraform_zip }}"
