---

- name: ensure requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_meta_packages: "{{ terraform_packages }}"

- name: fetch terraform info
  uri:
    url: https://www.terraform.io/downloads.html
    method: GET
    follow_redirects: "yes"
    return_content: yes
  register: terraform_info_raw
  check_mode: no
  until: terraform_info_raw is succeeded
  retries: 30
  delay: 10

- name: set terraform download url
  set_fact:
    terraform_zip: "{{ terraform_info_raw.content | regex_search(package_regex) }}"
  vars:
    package_regex: 'https://releases.*linux_amd64\.zip'
  check_mode: no

- name: ensure terraform is downloaded
  unarchive:
    src: "{{ terraform_zip }}"
    dest: "{{ terraform_path }}"
    remote_src: yes
    mode: 0755
  become: yes
