---

- name: ensure docker repo is present
  include_role:
    name: apt-repo-meta
  vars:
    apt_repo_meta_keys:
      - "{{ docker_apt_key }}"
    apt_repo_meta_repositories:
      - "{{ docker_apt_repo }}"

- name: ensure docker is installed
  include_role:
    name: apt-meta
  vars:
    apt_meta_packages: "{{ [ docker_package_name ] }}"

- name: ensure user is added to docker group
  become: yes
  user:
    append: yes
    groups: docker
    name: "{{ user }}"
    update_password: on_create
